keyStorePara=javax.net.ssl.keyStore
keyPassWordPara=javax.net.ssl.keyStorePassword

GWRuntime.env=PI

PI.domain=https://wugateway2pi.westernunion.net
PI.ipAddr=66.218.162.7
PI.keyStore=cert/WUPIGateway-pi.jks
PI.keyPassWord=Welcomepi@54321

PROD.domain=https://wugateway2.westernunion.net
PROD.ipAddr=66.218.162.5
PROD.keyStore=cert/keystore.jks
##PROD.keyPassWord=password01!
PROD.keyPassWord=kissslcertpsw

MTCN.input.folder=MTCN/input
MTCN.output.folder=MTCN/output

DAS.output.folder=DAS

Pricing.input.folder=Pricing/input
Pricing.output.folder=Pricing/output
###Pricing.output.folder=Pricing/PricingTable

XMLSamplesPath.DAS_Query=xmlsamples/DAS_Query
XMLSamplesPath.PI_MTCN=xmlsamples/PI_MTCN
XMLSamplesPath.PROD_Pricing=xmlsamples/PROD_Pricing
XMLSamplesPath.PI_Pricing=xmlsamples/PI_Pricing