GenMTCNRequest.serialNum=1
GenMTCNRequest.description=Create Testing MTCNs in batch

CountryCurrencyListRequest.serialNum=2
CountryCurrencyListRequest.description=Get Country Currency List
CountryCurrencyListRequest.dasName=GetCountriesCurrencies

USStateListRequest.serialNum=3
USStateListRequest.description=Get US State List
USStateListRequest.dasName=GetUSStateList

MexicoCityStateRequest.serialNum=4
MexicoCityStateRequest.description=Get Mexico City and State List
MexicoCityStateRequest.dasName=GetMexicoCityState

APNDynamicRequest.serialNum=5
APNDynamicRequest.description=Get APN Dynamic Template

PricingTableRequest.serialNum=6
PricingTableRequest.description=Get Pricing Table

DeliveryServiceListRequest.serialNum=7
DeliveryServiceListRequest.description=Get Delivery Service List

APNDataScopeRequest.serialNum=8
APNDataScopeRequest.description=Get APN Data Scope List

ExitRequest.serialNum=n
ExitRequest.description=No more request