smv.sender.name=<sender><name...</name>
smv.sender.name.assembler=com.wu.xmlhandler.GWSenderNameAssembler
smv.sender.address=<addr_line1>...</addr_line1>
smv.sender.address.assembler=com.wu.xmlhandler.SingleElementAssembler
smv.receiver.name=<receiver><name...</name>
smv.receiver.name.assembler=com.wu.xmlhandler.GWReceiverNameAssembler
smv.financials.amount=<financials>...</financials>
smv.financials.amount.assembler=com.wu.xmlhandler.GWAISFinancialAssembler
smv.payment_details.transaction_type=<transaction_type>...</transaction_type>
smv.payment_details.transaction_type.assembler=com.wu.xmlhandler.SingleElementAssembler
smv.payment_details.destination_country_currency=<destination_country_currency>...</destination_country_currency>
smv.payment_details.destination_country_currency.assembler=com.wu.xmlhandler.GWAISCountryCurrencyAssembler

sms.sender=<sender>...</sender>
sms.sender.assembler=com.wu.xmlhandler.CopyTagAssembler
sms.receiver=<receiver>...</receiver>
sms.receiver.assembler=com.wu.xmlhandler.CopyTagAssembler
sms.payment_details=<payment_details>...</payment_details>
sms.payment_details.assembler=com.wu.xmlhandler.CopyTagAssembler
sms.financials=<financials>...</financials>
sms.financials.assembler=com.wu.xmlhandler.CopyTagAssembler
sms.mtcn=<mtcn>...</mtcn>
sms.mtcn.assembler=com.wu.xmlhandler.CopyTagAssembler
sms.new_mtcn=<new_mtcn>...</new_mtcn>
sms.new_mtcn.assembler=com.wu.xmlhandler.CopyTagAssembler
sms.df_fields=<df_fields>...</df_fields>
sms.df_fields.assembler=com.wu.xmlhandler.CopyTagAssembler

fi.payment_details.transaction_type=<transaction_type>...</transaction_type>
fi.payment_details.transaction_type.assembler=com.wu.xmlhandler.SingleElementAssembler
fi.financials.amount=<financials>...</financials>
fi.financials.amount.assembler=com.wu.xmlhandler.GWAISFinancialAssembler
fi.payment_details.destination_country_currency=<destination_country_currency>...</destination_country_currency>
fi.payment_details.destination_country_currency.assembler=com.wu.xmlhandler.GWAISCountryCurrencyAssembler
fi.delivery_services.code=<delivery_services><code>...</code></delivery_services>
fi.delivery_services.code.assembler=com.wu.xmlhandler.SingleElementAssembler
fi.foreign_remote_system.counter_id=<counter_id>...</counter_id>
fi.foreign_remote_system.counter_id.assembler=com.wu.xmlhandler.SingleElementAssembler