fi.transaction_type=<transaction_type>...</transaction_type>
fi.transaction_type.assembler=com.wu.xmlhandler.SingleElementAssembler
fi.payment_details.principal_amount=<origination>...</country_iso_code>
fi.payment_details.principal_amount.assembler=com.wu.xmlhandler.GWBISOriginationAssembler
fi.payment_details.destination=<destination>...</country_iso_code>
fi.payment_details.destination.assembler=com.wu.xmlhandler.GWBISDestinationAssembler
fi.connector=<connector><id>...</id></connector>
fi.connector.assembler=com.wu.xmlhandler.SingleElementAssembler

smv.sender.name=<sender><name...</name>
smv.sender.name.assembler=com.wu.xmlhandler.GWSenderNameAssembler
smv.sender.address=<addr_line1>...</addr_line1>
smv.sender.address.assembler=com.wu.xmlhandler.SingleElementAssembler
smv.receiver.name=<receiver><name...</name>
smv.receiver.name.assembler=com.wu.xmlhandler.GWReceiverNameAssembler
smv.transaction_type=<transaction_type>...</transaction_type>
smv.transaction_type.assembler=com.wu.xmlhandler.CopyTagAssembler
smv.payment_details=<payment_details>...</payment_details>
smv.payment_details.assembler=com.wu.xmlhandler.CopyTagAssembler

sms.sender=<sender>...</sender>
sms.sender.assembler=com.wu.xmlhandler.CopyTagAssembler
sms.receiver=<receiver>...</receiver>
sms.receiver.assembler=com.wu.xmlhandler.CopyTagAssembler
sms.transaction_type=<transaction_type>...</transaction_type>
sms.transaction_type.assembler=com.wu.xmlhandler.CopyTagAssembler
sms.payment_details=<payment_details>...</payment_details>
sms.payment_details.assembler=com.wu.xmlhandler.CopyTagAssembler
sms.temp_transaction_id=<temp_transaction_id>...</temp_transaction_id>
sms.temp_transaction_id.assembler=com.wu.xmlhandler.CopyTagAssembler