search.mtcn=<mtcn>...</mtcn>
search.mtcn.assembler=com.wu.xmlhandler.SingleElementAssembler

refund.sender=<sender>...</sender>
refund.sender.assembler=com.wu.xmlhandler.CopyTagAssembler
refund.receiver=<receiver>...</receiver>
refund.receiver.assembler=com.wu.xmlhandler.CopyTagAssembler
refund.payment_details=<payment_details>...</payment_details>
refund.payment_details.assembler=com.wu.xmlhandler.CopyTagAssembler
refund.financials=<financials>...</financials>
refund.financials.assembler=com.wu.xmlhandler.CopyTagAssembler
refund.mtcn=<mtcn>...</mtcn>
refund.mtcn.assembler=com.wu.xmlhandler.CopyTagAssembler
refund.new_mtcn=<new_mtcn>...</new_mtcn>
refund.new_mtcn.assembler=com.wu.xmlhandler.CopyTagAssembler
refund.money_transfer_key=<money_transfer_key>...</money_transfer_key>
refund.money_transfer_key.assembler=com.wu.xmlhandler.CopyTagAssembler