queryfilter1=<queryfilter1>...</queryfilter1>
queryfilter1.assembler=com.wu.xmlhandler.SingleElementAssembler
queryfilter2=<queryfilter2>...</queryfilter2>
queryfilter2.assembler=com.wu.xmlhandler.SingleElementAssembler
queryfilter3=<queryfilter3>...</queryfilter3>
queryfilter3.assembler=com.wu.xmlhandler.SingleElementAssembler
queryfilter4=<queryfilter4>...</queryfilter4>
queryfilter4.assembler=com.wu.xmlhandler.SingleElementAssembler
queryfilter5=<queryfilter5>...</queryfilter5>
queryfilter5.assembler=com.wu.xmlhandler.SingleElementAssembler
queryfilter6=<queryfilter6>...</queryfilter6>
queryfilter6.assembler=com.wu.xmlhandler.SingleElementAssembler
queryfilter7=<queryfilter7>...</queryfilter7>
queryfilter7.assembler=com.wu.xmlhandler.SingleElementAssembler
queryfilter8=<queryfilter8>...</queryfilter8>
queryfilter8.assembler=com.wu.xmlhandler.SingleElementAssembler
queryfilter9=<queryfilter9>...</queryfilter9>
queryfilter9.assembler=com.wu.xmlhandler.SingleElementAssembler
queryfilter10=<queryfilter10>...</queryfilter10>
queryfilter10.assembler=com.wu.xmlhandler.SingleElementAssembler