
package com.wu.gw.model.ais;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DASInquiryPortType", targetNamespace = "http://www.westernunion.com/DAS_Service_H2H")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DASInquiryPortType {


    /**
     * 
     * @param h2HDasRequest
     * @return
     *     returns com.wu.gw.ais.XRSIDasReply
     * @throws DASServiceFault1
     */
    @WebMethod(operationName = "DAS_Service")
    @WebResult(name = "h2h-das-reply", targetNamespace = "http://www.westernunion.com/schema/xrsi", partName = "h2h-das-reply")
    public XRSIDasReply dasService(
        @WebParam(name = "h2h-das-request", targetNamespace = "http://www.westernunion.com/schema/xrsi", partName = "h2h-das-request")
        XRSIDasRequest h2HDasRequest)
        throws DASServiceFault1
    ;

}
