
package com.wu.gw.model.ais;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DAS_Service_H2H", targetNamespace = "http://www.westernunion.com/DAS_Service_H2H", wsdlLocation = "file:/ws/wsdl/DAS_Service_H2HService.wsdl")
public class DASServiceH2H
    extends Service
{

    private final static URL DASSERVICEH2H_WSDL_LOCATION;
    private final static WebServiceException DASSERVICEH2H_EXCEPTION;
    private final static QName DASSERVICEH2H_QNAME = new QName("http://www.westernunion.com/DAS_Service_H2H", "DAS_Service_H2H");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        
            /*URL base = DASServiceH2H.class.getResource("");
            
            String basePath = base.getPath();
            int basePathIndex = basePath.indexOf("WUServiceConsole.jar!");
            String parentPath = basePath.substring(0, basePathIndex);
            
        	String path = parentPath + "ws/wsdl/DAS_Service_H2HService.wsdl";
            url = new URL(path);*/
        	
            url = new URL("file:/C:/ws/wsdl/DAS_Service_H2HService.wsdl");
       
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DASSERVICEH2H_WSDL_LOCATION = url;
        DASSERVICEH2H_EXCEPTION = e;
    }

    public DASServiceH2H() {
        super(__getWsdlLocation(), DASSERVICEH2H_QNAME);
    }

    public DASServiceH2H(WebServiceFeature... features) {
        super(__getWsdlLocation(), DASSERVICEH2H_QNAME, features);
    }

    public DASServiceH2H(URL wsdlLocation) {
        super(wsdlLocation, DASSERVICEH2H_QNAME);
    }

    public DASServiceH2H(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DASSERVICEH2H_QNAME, features);
    }

    public DASServiceH2H(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DASServiceH2H(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DASInquiryPortType
     */
    @WebEndpoint(name = "SOAP_HTTP_Port")
    public DASInquiryPortType getSOAPHTTPPort() {
        return super.getPort(new QName("http://www.westernunion.com/DAS_Service_H2H", "SOAP_HTTP_Port"), DASInquiryPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DASInquiryPortType
     */
    @WebEndpoint(name = "SOAP_HTTP_Port")
    public DASInquiryPortType getSOAPHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.westernunion.com/DAS_Service_H2H", "SOAP_HTTP_Port"), DASInquiryPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DASSERVICEH2H_EXCEPTION!= null) {
            throw DASSERVICEH2H_EXCEPTION;
        }
        return DASSERVICEH2H_WSDL_LOCATION;
    }

}
