
package com.wu.gw.model.ais;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FeeInquiryPortType", targetNamespace = "http://www.westernunion.com/FeeInquiry_H2H")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FeeInquiryPortType {


    /**
     * 
     * @param feeInquiryRequest
     * @return
     *     returns com.wu.gw.ais.FeeInquiryReply
     * @throws FeeInquiryFault1
     */
    @WebMethod(operationName = "FeeInquiry")
    @WebResult(name = "fee-inquiry-reply", targetNamespace = "http://www.westernunion.com/schema/xrsi", partName = "fee-inquiry-reply")
    public FeeInquiryReply feeInquiry(
        @WebParam(name = "fee-inquiry-request", targetNamespace = "http://www.westernunion.com/schema/xrsi", partName = "fee-inquiry-request")
        FeeInquiryRequest feeInquiryRequest)
        throws FeeInquiryFault1
    ;

}
