
package com.wu.gw.model.ais;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PayStatusPortType", targetNamespace = "http://www.westernunion.com/PayStatus_H2H")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PayStatusPortType {


    /**
     * 
     * @param payStatusInquiryRequestData
     * @return
     *     returns com.wu.gw.ais.PayStatusInquiryReply
     * @throws PayStatusFault1
     */
    @WebMethod(operationName = "PayStatus")
    @WebResult(name = "pay-status-inquiry-reply", targetNamespace = "http://www.westernunion.com/schema/xrsi", partName = "pay-status-inquiry-reply")
    public PayStatusInquiryReply payStatus(
        @WebParam(name = "pay-status-inquiry-request-data", targetNamespace = "http://www.westernunion.com/schema/xrsi", partName = "pay-status-inquiry-request-data")
        PayStatusInquiryRequestData payStatusInquiryRequestData)
        throws PayStatusFault1
    ;

}
