
package com.wu.gw.model.ais;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReceiveMoneyPayPortType", targetNamespace = "http://www.westernunion.com/ReceiveMoneyPay_H2H")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReceiveMoneyPayPortType {


    /**
     * 
     * @param receiveMoneyPayRequest
     * @return
     *     returns com.wu.gw.ais.ReceiveMoneyPayReply
     * @throws ReceiveMoneyPayFault1
     */
    @WebMethod(operationName = "ReceiveMoneyPay", action = "ReceiveMoneyPay_Action")
    @WebResult(name = "receive-money-pay-reply", targetNamespace = "http://www.westernunion.com/schema/xrsi", partName = "receive-money-pay-reply")
    public ReceiveMoneyPayReply receiveMoneyPay(
        @WebParam(name = "receive-money-pay-request", targetNamespace = "http://www.westernunion.com/schema/xrsi", partName = "receive-money-pay-request")
        ReceiveMoneyPayRequest receiveMoneyPayRequest)
        throws ReceiveMoneyPayFault1
    ;

}
