
package com.wu.gw.model.ais;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReceiveMoneyPay_Service_H2H", targetNamespace = "http://www.westernunion.com/ReceiveMoneyPay_H2H", wsdlLocation = "file:/ws/wsdl/ReceiveMoneyPay_Service_H2HService.wsdl")
public class ReceiveMoneyPayServiceH2H
    extends Service
{

    private final static URL RECEIVEMONEYPAYSERVICEH2H_WSDL_LOCATION;
    private final static WebServiceException RECEIVEMONEYPAYSERVICEH2H_EXCEPTION;
    private final static QName RECEIVEMONEYPAYSERVICEH2H_QNAME = new QName("http://www.westernunion.com/ReceiveMoneyPay_H2H", "ReceiveMoneyPay_Service_H2H");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	
        	URL base = ReceiveMoneyPayServiceH2H.class.getResource("");
        	String path = "file:" + base.getPath() + "ws/wsdl/ReceiveMoneyPay_Service_H2HService.wsdl";
        	
            url = new URL(path);
        	
            //url = new URL("file:/C:/ws/wsdl/ReceiveMoneyPay_Service_H2HService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECEIVEMONEYPAYSERVICEH2H_WSDL_LOCATION = url;
        RECEIVEMONEYPAYSERVICEH2H_EXCEPTION = e;
    }

    public ReceiveMoneyPayServiceH2H() {
        super(__getWsdlLocation(), RECEIVEMONEYPAYSERVICEH2H_QNAME);
    }

    public ReceiveMoneyPayServiceH2H(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECEIVEMONEYPAYSERVICEH2H_QNAME, features);
    }

    public ReceiveMoneyPayServiceH2H(URL wsdlLocation) {
        super(wsdlLocation, RECEIVEMONEYPAYSERVICEH2H_QNAME);
    }

    public ReceiveMoneyPayServiceH2H(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECEIVEMONEYPAYSERVICEH2H_QNAME, features);
    }

    public ReceiveMoneyPayServiceH2H(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReceiveMoneyPayServiceH2H(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReceiveMoneyPayPortType
     */
    @WebEndpoint(name = "SOAP_HTTP_Port")
    public ReceiveMoneyPayPortType getSOAPHTTPPort() {
        return super.getPort(new QName("http://www.westernunion.com/ReceiveMoneyPay_H2H", "SOAP_HTTP_Port"), ReceiveMoneyPayPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReceiveMoneyPayPortType
     */
    @WebEndpoint(name = "SOAP_HTTP_Port")
    public ReceiveMoneyPayPortType getSOAPHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.westernunion.com/ReceiveMoneyPay_H2H", "SOAP_HTTP_Port"), ReceiveMoneyPayPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECEIVEMONEYPAYSERVICEH2H_EXCEPTION!= null) {
            throw RECEIVEMONEYPAYSERVICEH2H_EXCEPTION;
        }
        return RECEIVEMONEYPAYSERVICEH2H_WSDL_LOCATION;
    }

}
