
package com.wu.gw.model.ais;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReceiveMoneySearch_Service_H2H", targetNamespace = "http://www.westernunion.com/ReceiveMoneySearch_H2H", wsdlLocation = "file:/ws/wsdl/ReceiveMoneySearch_Service_H2HService.wsdl")
public class ReceiveMoneySearchServiceH2H
    extends Service
{

    private final static URL RECEIVEMONEYSEARCHSERVICEH2H_WSDL_LOCATION;
    private final static WebServiceException RECEIVEMONEYSEARCHSERVICEH2H_EXCEPTION;
    private final static QName RECEIVEMONEYSEARCHSERVICEH2H_QNAME = new QName("http://www.westernunion.com/ReceiveMoneySearch_H2H", "ReceiveMoneySearch_Service_H2H");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	
        	URL base = ReceiveMoneySearchServiceH2H.class.getResource("");
        	String path = "file:" + base.getPath() + "ws/wsdl/ReceiveMoneySearch_Service_H2HService.wsdl";
        	
            url = new URL(path);
        	
            //url = new URL("file:/C:/ws/wsdl/ReceiveMoneySearch_Service_H2HService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECEIVEMONEYSEARCHSERVICEH2H_WSDL_LOCATION = url;
        RECEIVEMONEYSEARCHSERVICEH2H_EXCEPTION = e;
    }

    public ReceiveMoneySearchServiceH2H() {
        super(__getWsdlLocation(), RECEIVEMONEYSEARCHSERVICEH2H_QNAME);
    }

    public ReceiveMoneySearchServiceH2H(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECEIVEMONEYSEARCHSERVICEH2H_QNAME, features);
    }

    public ReceiveMoneySearchServiceH2H(URL wsdlLocation) {
        super(wsdlLocation, RECEIVEMONEYSEARCHSERVICEH2H_QNAME);
    }

    public ReceiveMoneySearchServiceH2H(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECEIVEMONEYSEARCHSERVICEH2H_QNAME, features);
    }

    public ReceiveMoneySearchServiceH2H(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReceiveMoneySearchServiceH2H(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReceiveMoneySearchPortType
     */
    @WebEndpoint(name = "SOAP_HTTP_Port")
    public ReceiveMoneySearchPortType getSOAPHTTPPort() {
        return super.getPort(new QName("http://www.westernunion.com/ReceiveMoneySearch_H2H", "SOAP_HTTP_Port"), ReceiveMoneySearchPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReceiveMoneySearchPortType
     */
    @WebEndpoint(name = "SOAP_HTTP_Port")
    public ReceiveMoneySearchPortType getSOAPHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.westernunion.com/ReceiveMoneySearch_H2H", "SOAP_HTTP_Port"), ReceiveMoneySearchPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECEIVEMONEYSEARCHSERVICEH2H_EXCEPTION!= null) {
            throw RECEIVEMONEYSEARCHSERVICEH2H_EXCEPTION;
        }
        return RECEIVEMONEYSEARCHSERVICEH2H_WSDL_LOCATION;
    }

}
