
package com.wu.gw.model.ais;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReceiveMoneySearchPortType", targetNamespace = "http://www.westernunion.com/ReceiveMoneySearch_H2H")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReceiveMoneySearchPortType {


    /**
     * 
     * @param receiveMoneySearchRequest
     * @return
     *     returns com.wu.gw.ais.ReceiveMoneySearchReply
     * @throws ReceiveMoneySearchFault1
     */
    @WebMethod(operationName = "ReceiveMoneySearch", action = "ReceiveMoneySearch_Action")
    @WebResult(name = "receive-money-search-reply", targetNamespace = "http://www.westernunion.com/schema/xrsi", partName = "receive-money-search-reply")
    public ReceiveMoneySearchReply receiveMoneySearch(
        @WebParam(name = "receive-money-search-request", targetNamespace = "http://www.westernunion.com/schema/xrsi", partName = "receive-money-search-request")
        ReceiveMoneySearchRequest receiveMoneySearchRequest)
        throws ReceiveMoneySearchFault1
    ;

}
