
package com.wu.gw.model.ais;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "error-reply", targetNamespace = "http://www.westernunion.com/schema/xrsi")
public class ReceiveMoneyPayFault1
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErrorReply faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ReceiveMoneyPayFault1(String message, ErrorReply faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ReceiveMoneyPayFault1(String message, ErrorReply faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.wu.gw.ais.ErrorReply
     */
    public ErrorReply getFaultInfo() {
        return faultInfo;
    }

}
