
package com.wu.gw.model.ais;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendMoneyStorePortType", targetNamespace = "http://www.westernunion.com/SendMoneyStore_H2H")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendMoneyStorePortType {


    /**
     * 
     * @param sendMoneyStoreRequest
     * @return
     *     returns com.wu.gw.ais.SendMoneyStoreReply
     * @throws SendMoneyStoreH2HFault1
     */
    @WebMethod(operationName = "SendMoneyStore_H2H")
    @WebResult(name = "send-money-store-reply", targetNamespace = "http://www.westernunion.com/schema/xrsi", partName = "send-money-store-reply")
    public SendMoneyStoreReply sendMoneyStoreH2H(
        @WebParam(name = "send-money-store-request", targetNamespace = "http://www.westernunion.com/schema/xrsi", partName = "send-money-store-request")
        SendMoneyStoreRequest sendMoneyStoreRequest)
        throws SendMoneyStoreH2HFault1
    ;

}
