
package com.wu.gw.model.ais;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendMoneyValidatePortType", targetNamespace = "http://www.westernunion.com/SendMoneyValidate_H2H")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendMoneyValidatePortType {


    /**
     * 
     * @param sendMoneyValidationRequest
     * @return
     *     returns com.wu.gw.ais.SendMoneyValidationReply
     * @throws SendmoneyValidationFault1
     */
    @WebMethod
    @WebResult(name = "send-money-validation-reply", targetNamespace = "http://www.westernunion.com/schema/xrsi", partName = "send-money-validation-reply")
    public SendMoneyValidationReply sendmoneyValidation(
        @WebParam(name = "send-money-validation-request", targetNamespace = "http://www.westernunion.com/schema/xrsi", partName = "send-money-validation-request")
        SendMoneyValidationRequest sendMoneyValidationRequest)
        throws SendmoneyValidationFault1
    ;

}
