
package com.wu.gw.model.ais;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SendmoneyValidation_Service_H2H", targetNamespace = "http://www.westernunion.com/SendMoneyValidate_H2H", wsdlLocation = "file:/ws/wsdl/SendMoneyValidation_Service_H2HService.wsdl")
public class SendmoneyValidationServiceH2H
    extends Service
{

    private final static URL SENDMONEYVALIDATIONSERVICEH2H_WSDL_LOCATION;
    private final static WebServiceException SENDMONEYVALIDATIONSERVICEH2H_EXCEPTION;
    private final static QName SENDMONEYVALIDATIONSERVICEH2H_QNAME = new QName("http://www.westernunion.com/SendMoneyValidate_H2H", "SendmoneyValidation_Service_H2H");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	
        	URL base = SendmoneyValidationServiceH2H.class.getResource("");
        	//String path = "file:" + base.getPath() + "ws/wsdl/SendMoneyValidation_Service_H2HService.wsdl";
        	String path = base.getPath() + "ws/wsdl/SendMoneyValidation_Service_H2HService.wsdl";
        	
            url = new URL(path);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENDMONEYVALIDATIONSERVICEH2H_WSDL_LOCATION = url;
        SENDMONEYVALIDATIONSERVICEH2H_EXCEPTION = e;
    }

    public SendmoneyValidationServiceH2H() {
        super(__getWsdlLocation(), SENDMONEYVALIDATIONSERVICEH2H_QNAME);
    }

    public SendmoneyValidationServiceH2H(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENDMONEYVALIDATIONSERVICEH2H_QNAME, features);
    }

    public SendmoneyValidationServiceH2H(URL wsdlLocation) {
        super(wsdlLocation, SENDMONEYVALIDATIONSERVICEH2H_QNAME);
    }

    public SendmoneyValidationServiceH2H(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENDMONEYVALIDATIONSERVICEH2H_QNAME, features);
    }

    public SendmoneyValidationServiceH2H(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendmoneyValidationServiceH2H(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendMoneyValidatePortType
     */
    @WebEndpoint(name = "SOAP_HTTP_Port")
    public SendMoneyValidatePortType getSOAPHTTPPort() {
        return super.getPort(new QName("http://www.westernunion.com/SendMoneyValidate_H2H", "SOAP_HTTP_Port"), SendMoneyValidatePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendMoneyValidatePortType
     */
    @WebEndpoint(name = "SOAP_HTTP_Port")
    public SendMoneyValidatePortType getSOAPHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.westernunion.com/SendMoneyValidate_H2H", "SOAP_HTTP_Port"), SendMoneyValidatePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENDMONEYVALIDATIONSERVICEH2H_EXCEPTION!= null) {
            throw SENDMONEYVALIDATIONSERVICEH2H_EXCEPTION;
        }
        return SENDMONEYVALIDATIONSERVICEH2H_WSDL_LOCATION;
    }

}
