spring.application.name=mywugateway
server.port=9090

##spring.datasource.driver-class-name=com.mysql.jdbc.Driver
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##spring.datasource.url=jdbc:mysql://localhost:3306/mywudb
##spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
##spring.datasource.username=root
##spring.datasource.password=binw@1213

spring.datasource.url=jdbc:postgresql://localhost:5432/mywudb
spring.datasource.username=mywu
spring.datasource.password=binw@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource

###mybatis.mapper-locations=classpath:mapper/*.xml

###logging.level.*=debug

spring.security.user.name=bin
spring.security.user.password=123

mybatis.mapper-locations=classpath:mapper/*.xml

MTCN.input.folder=MTCN/input
MTCN.output.folder=MTCN/output
